import { Token, Organization, User, Marketplace, MediaChannel, CampaignTemplate, Vendor, Catalog, Product, MarketingCampaign, MarketingAd, Result, Entitlement } from '../generated/graphql';
declare type Fields<T> = {
    [key in NonNullable<keyof T>]: keyof T;
};
export declare type TokenFields = Fields<Token>;
export declare const TokenFields: Fields<Token>;
export declare type OrganizationFields = Fields<Organization>;
export declare const OrganizationFields: Fields<Organization>;
export declare type UserFields = Fields<User>;
export declare const UserFields: Fields<User>;
export declare type MarketplaceFields = Fields<Marketplace>;
export declare const MarketplaceFields: Fields<Marketplace>;
export declare type MediaChannelFields = Fields<MediaChannel>;
export declare const MediaChannelFields: Fields<MediaChannel>;
export declare type CampaignTemplateFields = Fields<CampaignTemplate>;
export declare const CampaignTemplateFields: Fields<CampaignTemplate>;
export declare type VendorFields = Fields<Vendor>;
export declare const VendorFields: Fields<Vendor>;
export declare type CatalogFields = Fields<Catalog>;
export declare const CatalogFields: Fields<Catalog>;
export declare type ProductFields = Fields<Product>;
export declare const ProductFields: Fields<Product>;
export declare type MarketingCampaignFields = Fields<MarketingCampaign>;
export declare const MarketingCampaignFields: Fields<MarketingCampaign>;
export declare type MarketingAdFields = Fields<MarketingAd>;
export declare const MarketingAdFields: Fields<MarketingAd>;
export declare type ResultFields = Fields<Result>;
export declare const ResultFields: Fields<Result>;
export declare type EntitlementFields = Fields<Entitlement>;
export declare const EntitlementFields: Fields<Entitlement>;
export {};
